// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDabGQKujaxPHN4YJ7EAypYu_5SxgPZ4YI',
    appId: '1:288213347285:web:86b7f550f6b33b54d76b5c',
    messagingSenderId: '288213347285',
    projectId: 'gajinaik-database',
    authDomain: 'gajinaik-database.firebaseapp.com',
    storageBucket: 'gajinaik-database.firebasestorage.app',
    measurementId: 'G-KRMSJZ34GM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6EgQt4CgBCFNgsLI0L9GAhmhnFYyT8Ck',
    appId: '1:288213347285:android:e3943f558cab4121d76b5c',
    messagingSenderId: '288213347285',
    projectId: 'gajinaik-database',
    storageBucket: 'gajinaik-database.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlHsWCNDAmgYUaTVTbkdogUslNFCt5bU4',
    appId: '1:288213347285:ios:dc921c4355675464d76b5c',
    messagingSenderId: '288213347285',
    projectId: 'gajinaik-database',
    storageBucket: 'gajinaik-database.firebasestorage.app',
    iosBundleId: 'com.example.gajiNaik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlHsWCNDAmgYUaTVTbkdogUslNFCt5bU4',
    appId: '1:288213347285:ios:dc921c4355675464d76b5c',
    messagingSenderId: '288213347285',
    projectId: 'gajinaik-database',
    storageBucket: 'gajinaik-database.firebasestorage.app',
    iosBundleId: 'com.example.gajiNaik',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDabGQKujaxPHN4YJ7EAypYu_5SxgPZ4YI',
    appId: '1:288213347285:web:0bd732dbd02a2a31d76b5c',
    messagingSenderId: '288213347285',
    projectId: 'gajinaik-database',
    authDomain: 'gajinaik-database.firebaseapp.com',
    storageBucket: 'gajinaik-database.firebasestorage.app',
    measurementId: 'G-CX0CS1PWQ2',
  );
}
